version: "3.8"
services:
  backend:
    build:
      context: ./backend
    expose:
      - "8080"   # expose only to docker network, not host
  
  frontend:
    build:
      context: ./frontend
    expose:
      - "80"     # expose only to docker network, not host
  
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"   # only if you need external DB access, otherwise just expose internally
  
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"   # public entry point
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  mongo-data:
    driver: local
