version : "3.8"
services:
  service1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
  service2:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"